import { WorkoutRoutine } from './types';

export const WORKOUT_ROUTINES: WorkoutRoutine[] = [
  {
    id: 'power-foundations',
    title: 'Power Foundations',
    description: 'Full-body strength session with smooth progressive overload.',
    duration: 38,
    level: 'beginner',
    focus: 'Full Body',
    spotifyPlaylistId: '37i9dQZF1DX3PFzdbtx1Us',
    heroImage: 'https://images.unsplash.com/photo-1518611012118-696072aa579a',
    warmup: {
      id: 'warmup-1',
      title: 'Mobility Ignition',
      duration: 6,
      intensity: 'low',
      exercises: [
        {
          id: 'wu1',
          name: 'World’s Greatest Stretch',
          workDuration: 45,
          restDuration: 15,
          cues: ['Deep inhale', 'Keep hips square', 'Reach tall'],
        },
        {
          id: 'wu2',
          name: 'Bodyweight Squat Flow',
          workDuration: 45,
          restDuration: 15,
          cues: ['Press through heels', 'Open chest', 'Exhale up'],
        },
        {
          id: 'wu3',
          name: 'Arm Circles',
          workDuration: 45,
          restDuration: 15,
          cues: ['Control the tempo', 'Reverse halfway'],
        },
      ],
    },
    mainSets: [
      {
        id: 'block-1',
        title: 'Strength Ladder',
        duration: 22,
        intensity: 'moderate',
        exercises: [
          {
            id: 'ex1',
            name: 'Goblet Squat',
            workDuration: 60,
            restDuration: 20,
            cues: ['Brace core', 'Drive knees out', 'Control descent'],
          },
          {
            id: 'ex2',
            name: 'Single-Arm Row',
            workDuration: 60,
            restDuration: 20,
            cues: ['Hinge at hips', 'Pull to ribcage', 'Squeeze shoulder blade'],
          },
          {
            id: 'ex3',
            name: 'Tempo Push-Up',
            workDuration: 45,
            restDuration: 30,
            cues: ['3-sec lower', 'Stack shoulders over wrists'],
          },
        ],
      },
      {
        id: 'block-2',
        title: 'Core Finisher',
        duration: 10,
        intensity: 'high',
        exercises: [
          {
            id: 'ex4',
            name: 'Plank Shoulder Tap',
            workDuration: 40,
            restDuration: 20,
            cues: ['Feet wider than hips', 'Minimize sway'],
          },
          {
            id: 'ex5',
            name: 'Russian Twist',
            workDuration: 40,
            restDuration: 20,
            cues: ['Keep spine long', 'Breathe through transitions'],
          },
          {
            id: 'ex6',
            name: 'Hollow Hold',
            workDuration: 30,
            restDuration: 30,
            cues: ['Lower back imprinted', 'Reach long'],
          },
        ],
      },
    ],
    cooldown: {
      id: 'cooldown-1',
      title: 'Release & Recover',
      duration: 6,
      intensity: 'low',
      exercises: [
        {
          id: 'cd1',
          name: 'Supine Twist',
          workDuration: 60,
          restDuration: 0,
          cues: ['Let shoulder blades melt', 'Breathe deep into ribs'],
        },
        {
          id: 'cd2',
          name: 'Child’s Pose',
          workDuration: 60,
          restDuration: 0,
          cues: ['Reach forward', 'Relax hips towards heels'],
        },
      ],
    },
  },
  {
    id: 'athletic-hiit',
    title: 'Athletic HIIT Remix',
    description: 'Explosive intervals with DJ-curated drops to drive intensity.',
    duration: 32,
    level: 'intermediate',
    focus: 'Conditioning',
    spotifyPlaylistId: '37i9dQZF1DX2try9tv0z7p',
    heroImage: 'https://images.unsplash.com/photo-1574680096145-d05b474e2155',
    warmup: {
      id: 'warmup-2',
      title: 'Pulse Primer',
      duration: 5,
      intensity: 'low',
      exercises: [
        {
          id: 'hiit-wu1',
          name: 'Jog + High Knees',
          workDuration: 60,
          restDuration: 0,
          cues: ['Stay light', 'Drive arms'],
        },
        {
          id: 'hiit-wu2',
          name: 'Inchworm to Plank',
          workDuration: 45,
          restDuration: 15,
          cues: ['Shift weight forward', 'Strong plank line'],
        },
      ],
    },
    mainSets: [
      {
        id: 'hiit-block-1',
        title: 'Power Intervals',
        duration: 18,
        intensity: 'high',
        exercises: [
          {
            id: 'hiit-ex1',
            name: 'Squat Jumps',
            workDuration: 30,
            restDuration: 15,
            cues: ['Soft landing', 'Explode up on beat'],
          },
          {
            id: 'hiit-ex2',
            name: 'Mountain Climbers',
            workDuration: 30,
            restDuration: 15,
            cues: ['Drive knees fast', 'Keep shoulders stacked'],
          },
          {
            id: 'hiit-ex3',
            name: 'Alternating Reverse Lunge',
            workDuration: 40,
            restDuration: 20,
            cues: ['Push front heel', 'Maintain tempo with track'],
          },
        ],
      },
      {
        id: 'hiit-block-2',
        title: 'Beat Drop Finisher',
        duration: 9,
        intensity: 'high',
        exercises: [
          {
            id: 'hiit-ex4',
            name: 'Burpee to Jack',
            workDuration: 30,
            restDuration: 15,
            cues: ['Hit the floor', 'Jump wide on drop'],
          },
          {
            id: 'hiit-ex5',
            name: 'Speed Skaters',
            workDuration: 30,
            restDuration: 15,
            cues: ['Reach for the ground', 'Explode laterally'],
          },
        ],
      },
    ],
    cooldown: {
      id: 'hiit-cooldown',
      title: 'Breath Control',
      duration: 5,
      intensity: 'low',
      exercises: [
        {
          id: 'hiit-cd1',
          name: 'Box Breathing',
          workDuration: 60,
          restDuration: 0,
          cues: ['4 in · 4 hold · 4 out · 4 hold'],
        },
        {
          id: 'hiit-cd2',
          name: 'Standing Quad Stretch',
          workDuration: 60,
          restDuration: 0,
          cues: ['Knees together', 'Hips forward'],
        },
      ],
    },
  },
];
